error: make WrappedErr wrap inner in Box<dyn>
Originally, we went with a generic route which could have been more
efficient. However, we ended up using either a `Box<dyn Error>` or a
`Box<dyn Error + Send>` as inner type for literally `WrappedErr`. And we
likely would for the remaining ones we'll introduce from now on.